server:
  port: 8080
spring:
  application:
    name: "cryptoManager"
  datasource:
    url: "jdbc:mysql://localhost:3306/crypto_manager"
    username: "root"
    password: "PZAdcn67."
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: "update"
    show-sql: true
    databasePlatform: "org.hibernate.dialect.MySQLDialect"
  security:
    jwt:
      secret: "jsd"
      expiration-ms: 5000
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null

